import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/header/Header.jsx";
import Introduction from "../components/Introduction/Introduction.jsx";
import About from "../components/about/About.jsx";
import Projects from "../components/projects/Projects.jsx";
import Contact from "../components/contact/Contact.jsx";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nicolas Alonso Froeling</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <Introduction />
      <About />
      <Projects />
      <Contact />
    </div>
  );
}
