import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/header/Header.jsx";
import Introduction from "../components/Introduction/Introduction";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nicolas Alonso Froeling</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Introduction />
    </div>
  );
}
